import type { NextPage } from "next";
import Head from "next/head";
import Header from "@components/Header";

const Home: NextPage = () => {
  return (
    <div className="bg-forest">
      <div className="bg-black bg-opacity-80 text-white">
        <Head>
          <title>Personal Website</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="container">
          <Header />
        </main>
      </div>
    </div>
  );
};

export default Home;
