import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "@components/Navbar";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Personal Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <Navbar />
        <div>Home</div>
      </main>
    </div>
  );
};

export default Home;
